sudo: required

language: node_js
node_js:
  - 12

install:
  - npm install

jobs:
  allow_failures:
    - env: ALLOWED_TO_FAIL=true

  include:
    - stage: audit
      env: ALLOWED_TO_FAIL=true
      script: npm run audit

    - stage: deploy
      deploy:
        edge: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master

stages:
  - audit
  - deploy
